apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongo-service
  template:
    metadata:
      labels:
        app: auth-mongo-service
    spec:
      containers:
        - name: auth-mongo-service
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-service
spec:
  selector:
    app: auth-mongo-service
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017